### PR TITLE
using native node fetch implementation

### PR DESCRIPTION
**Pull request by muturgan**
Hello Jason! How are you?  

Currently I looking for an API testing tool for our new project. Previously I had a little experience with supertest. But I don't like it because of it contains a lot of vulnerable legacy dependencies. So I think about an alternative now. I found your great project and it looks well.  

But then I thought that it is possible to go further. You have @types/node v18 in dependencies. But since 18th version node have a native fetch support. So I think it could be nice to drop a non-necessary node-fetch dependency.  

Also I suggest to drop a @types/express dependency. In fact not each project use express and not each project use typesctipt. Probably not needed force users to install a dependency that useless for they. So I replaced this dependency with a helper interface that make it able to pass an express instance to a testing function.

Also I thought that "fetch" is a reserved global keyword not so it is incorrect to override it. So I using a "request" name like supertest do it.  

Hope I'm not too intrusive with these changes.
Best wishes!

### CODE REVIEW

**Comment by talentlessguy** [comment]
@jwalton could you review this plz? 🙏

**Comment by jwalton** [comment]
I’m very interested in having a look at this.  From the description it sounds fantastic.  But, I’ve got a touch of strep throat right now and a 102 fever so it might take me a couple of days to review.  If you don’t hear back from me by next week, please feel free to pester me.  ;)

**Comment by talentlessguy** [comment]
@jwalton oof I'm really sorry about your sickness and I hope you get better soon! There's nothing urgent, just thought to ping

**Comment by jwalton** [comment]
No worries.  I get too many GitHub notifications and it’s easy to forget about them.  Pinging me is the best way to get me merge something.  :)On Oct 26, 2023, at 18:40, v1rtl ***@***.***> wrote:﻿
@jwalton oof I'm really sorry about your sickness and I hope you get better soon! There's nothing urgent, just thought to ping

**Comment by muturgan** [comment]
@jwalton Damn! 102 degrees! I had 41 when I was sick with coronavirus. It felt like I was dying. It's scary to imagine what you're experiencing. I sincerely wish you to get better soon.

**Comment by jwalton** [comment]
One thing I'm curious about - why rename `makeFetch` to `makeRequest` and `fetch` to `request`?

**Comment by jwalton** [comment]
Sorry that took so insanely long.  :(  Thank you so much for doing this.  I really like that this has no external dependencies now.

I did rename `makeRequest` back to `makeFetch` and `request` back to `fetch`.  I'd rather not add more burden to someone upgrading to this library than required, and actually I like that `const fetch = makeFetch()` elides the native fetch.  You can always `import { fetch as request } from 'supertest-fetch';` if you want to rename them in your code.

Semantic-release should push a release in just a few minutes...

**Pull request merged**
